/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SimpleJPX */

#ifndef _Included_SimpleJPX
#define _Included_SimpleJPX
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     SimpleJPX
 * Method:    parse_GPX
 * Signature: ()LGPX; // This signature needs to be correct, pointing to the actual GPX class.
 */
JNIEXPORT jobject JNICALL Java_SimpleJPX_SimpleJPX_parseGPX
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL
Java_com_lazarus_run_1track1_SimpleJPX_SimpleJPX_wtb(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
